services:
  opensearch-exporter:
    build: .
    container_name: opensearch-exporter
    ports:
      - "8080:80"
    restart: unless-stopped

  metrics-server:
    build:
      context: .
      dockerfile: Dockerfile.metrics
    container_name: metrics-server
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./metrics.txt:/app/metrics.txt
  