FROM node:18-alpine

WORKDIR /app

# Установка TypeScript и ts-node глобально
RUN npm install -g typescript ts-node @types/node

# Копирование package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm install

# Копирование исходного кода
COPY . .

# Запуск сервера метрик
CMD ["ts-node", "-P", "tsconfig.metrics.json", "src/metrics-server.ts"]