# version: '3.8' # - if docker compose not v2
services:
  opensearch-exporter:
    build: .
    container_name: opensearch-exporter
    ports:
      - "8080:80"
    restart: unless-stopped

  metrics:
    build:
      context: .
      dockerfile: Dockerfile.metrics
    container_name: opensearch-exporter-metrics
    ports:
      - "9090:9090"
    restart: unless-stopped
