# # version: '3'  - if docker compose not v2
# services:
#   opensearch:
#     image: opensearchproject/opensearch:2.11.1
#     container_name: opensearch
#     environment:
#       - bootstrap.memory_lock=true
#       - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"

#       # Настройки безопасности
#       - "DISABLE_SECURITY_PLUGIN=false"
#       - "plugins.security.ssl.http.enabled=true"
#       - "plugins.security.ssl.transport.enabled=true"

#       # CORS настройки
#       - "http.cors.enabled=true"
#       - "http.cors.allow-origin=*"
      # - "http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE"
      # - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"

#       # Настройки single-node
#       - "discovery.type=single-node"

#       # Демо-конфигурация (используйте false для production)
#       - "DISABLE_INSTALL_DEMO_CONFIG=false"
#       - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin" # Стандартный пароль

#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#       nofile:
#         soft: 65536
#         hard: 65536
#     volumes:
#       - opensearch-data:/usr/share/opensearch/data
#     ports:
#       - "9200:9200"
#       - "9600:9600"
#     networks:
#       - opensearch-net

# volumes:
#   opensearch-data:

# networks:
#   opensearch-net:

version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node1
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=false"
      - "plugins.security.ssl.http.enabled=true"
      - "plugins.security.ssl.transport.enabled=true"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "cluster.name=opensearch-cluster"
      - "node.name=opensearch-node1"
      - "discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3"
      - "cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3"
      - "DISABLE_INSTALL_DEMO_CONFIG=false"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - opensearch-net

  opensearch-node2:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node2
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=false"
      - "plugins.security.ssl.http.enabled=true"
      - "plugins.security.ssl.transport.enabled=true"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "cluster.name=opensearch-cluster"
      - "node.name=opensearch-node2"
      - "discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3"
      - "cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3"
      - "DISABLE_INSTALL_DEMO_CONFIG=false"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-node3:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node3
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=false"
      - "plugins.security.ssl.http.enabled=true"
      - "plugins.security.ssl.transport.enabled=true"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "cluster.name=opensearch-cluster"
      - "node.name=opensearch-node3"
      - "discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3"
      - "cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3"
      - "DISABLE_INSTALL_DEMO_CONFIG=false"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data3:/usr/share/opensearch/data
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:
  opensearch-data3:

networks:
  opensearch-net:
